// ============================================================================
// Controller runtime data
// ============================================================================
// Defines the commands, gain matrices, shared signals, reports, and log records
// exchanged between the control, interface, and reporting modules.
#pragma once

#include "controller_config.h"

/// Stores the equivalent point-force disturbance and its joint-space torque.
struct AutomaticDisturbance {
  double scale = 0.0;             // Time-dependent force scale [-].
  double torque_scale = 1.0;      // Torque-limit scale [-].
  Vec3 point_base = Vec3::Zero(); // Force application point in base frame [m].
  Vec3 force_base = Vec3::Zero(); // Applied force in base frame [N].
  Vec7 tau = Vec7::Zero();        // Equivalent joint torque [N m].
};

/// Stores one chronological sample of the controller state and command.
/// Cartesian positions, forces, and moments are expressed in the base frame
/// unless a field name states another frame.
struct LogData {
  double time;          // Time from run start [s].
  int state;            // Encoded ControlState value [-].
  int nullspace_mode;   // Encoded NullspaceMode value [-].

  Vec3 p_EE;                    // Measured TCP position [m].
  Vec3 p_d;                     // Desired TCP position [m].
  Vec3 tool_contact_point;      // Measured tool-feature position [m].
  Vec3 first_contact_tcp;       // TCP position at first contact [m].
  Vec3 first_contact_point;     // Tool-feature position at first contact [m].
  Vec3 edge_target;             // Desired tool-feature position [m].
  Vec3 tool_contact_offset_ee;  // Feature offset in EE frame [m].
  Vec3 p_CoC;   // Centre of compliance, p_TCP + r_c [m]. Equals p_EE when the
                // lever is zero, so the centre is the TCP in that case.
  Vec3 r_eff;   // Lever the contact force acts through, p_contact - p_CoC [m].

  Vec3 e_p;  // Translational error p_d - p_EE [m].
  Vec3 e_R;  // Orientation error in base frame [rad].
  Vec3 angular_deviation_surface; // Deviation in [tangent1,tangent2,normal] [rad].
  double angular_deviation;       // Residual tool-to-plane deviation [rad].
  double t_align;                 // Time from first contact at which the
                                  // deviation first fell inside the tolerance
                                  // and stayed there [s]; negative until then.

  Vec3 pdot;    // Measured TCP linear velocity [m/s].
  Vec3 pdot_d;  // Desired TCP linear velocity [m/s].
  Vec3 omega;   // Measured angular velocity in base frame [rad/s].

  Vec3 f;                    // Commanded Cartesian force [N].
  Vec3 m;                    // Commanded Cartesian moment [N m].
  Vec3 external_force;       // O_F_ext_hat_K force component [N].
  Vec3 external_moment;      // O_F_ext_hat_K moment component [N m].
  Vec3 external_force_K_base;  // K_F_ext_hat_K force rotated into base axes [N].
  Vec3 external_moment_K_base; // K_F_ext_hat_K moment rotated into base axes [N m].
  Vec3 r_K_TCP_base;         // Offset p_K - p_TCP in base axes [m].
  Vec3 setup_Dp_used;        // Active setup damping in [t1,t2,n] [N s/m].
  Vec3 setup_DR_used;        // Active setup damping in [t1,t2,n] [N m s/rad].
  Vec3 contact_force_bias;   // External-force bias captured at contact [N].
  Vec3 contact_moment_bias;  // External-moment bias captured at contact [N m].
  double push;               // Virtual surface penetration [m].

  AutomaticDisturbance disturbance; // Applied disturbance state.

  double tau_nullspace_norm; // Nullspace-torque Euclidean norm [N m].
  double nullspace_damping;  // Active damping coefficient [N m s/rad].
  Vec7 tau_cmd;              // Final commanded joint torque [N m].
};

// ---------------------------------------------------------------------------
// Commands and state reports
// ---------------------------------------------------------------------------

/// Defines the translational reference generated by the active state.
struct DesiredTranslationCommand {
  Vec3 p_d;     // Desired TCP position in base frame [m].
  Vec3 pdot_d;  // Desired TCP linear velocity in base frame [m/s].
};

/// Stores the diagonal Cartesian inertia estimate in the selected task frame.
struct CartesianInertiaEstimate {
  Vec3 translational = Vec3::Ones(); // Translational inertia [kg].
  Vec3 rotational = Vec3::Ones();    // Rotational inertia [kg m^2].
  bool valid = false;                // Indicates a valid finite estimate.
};

/// Stores the state, wrench, and active gains captured when contact establishment ends.
struct ContactEstablishmentReport {
  // Defining the state termination and measured wrench changes.
  bool stopped_on_moment = false;   // true when the moment threshold ends contact establishment.
  double state_time = 0.0;          // Contact-establishment duration [s].
  double df_ext_norm = 0.0;         // Norm of the force change since contact [N].
  double m_tcp_norm = 0.0;          // Norm of that change about the TCP [N m].
  double t_align = -1.0;            // Alignment time [s], negative if the
                                    // deviation never settled inside the
                                    // tolerance for the required hold.
  double t_align_fraction = -1.0;   // Time the deviation first fell below the
                                    // configured fraction of its value at
                                    // first contact [s], negative if never.
  double deviation_min_deg = 0.0;   // Smallest deviation reached [deg].
  double t_deviation_min = 0.0;     // When it was reached [s]. Both are always
                                    // defined, so a condition that never
                                    // aligns still reports how close it came.

  // Defining the final pose and contact wrench in the base frame.
  Vec3 p_EE = Vec3::Zero();                 // Final TCP position [m].
  Mat3 R_EE = Mat3::Identity();             // Final EE orientation [-].
  Vec3 tool_contact_point = Vec3::Zero();   // Final tool-feature position [m].
  Vec3 external_force = Vec3::Zero();       // Final external force [N].
  Vec3 m_contact = Vec3::Zero();            // Moment about the contact point [N m].

  // Defining the first-contact reference in the base frame.
  Vec3 first_contact_tcp = Vec3::Zero();    // TCP position at contact [m].
  Vec3 first_contact_point = Vec3::Zero();  // Tool-feature position at contact [m].
  Mat3 R_contact_start = Mat3::Identity();  // EE orientation at contact [-].
  Vec3 contact_force_bias = Vec3::Zero();   // Captured force bias [N].

  // Defining the active contact establishment impedance in base coordinates.
  Mat3 Kp = Mat3::Zero(); // Translational stiffness [N/m].
  Mat3 Dp = Mat3::Zero(); // Translational damping [N s/m].
  Mat3 KR = Mat3::Zero(); // Rotational stiffness [N m/rad].
  Mat3 DR = Mat3::Zero(); // Rotational damping [N m s/rad].
};

// ----------------------------------------------------------------------------
// Runtime state and state data
// ----------------------------------------------------------------------------

/// Stores thread-safe operator requests consumed by the real-time loop.
struct KeyboardSignals {
  std::atomic<bool> stop_requested{false};      // Requests a controlled stop.
  std::atomic<bool> proceed_requested{false};   // Continues after pose recapture.
  std::atomic<bool> guide_requested{false};     // Requests manual guidance.
  std::atomic<char> guidance_menu_key{0};       // Selected guidance action key.
  std::atomic<bool> guided_hold_selector_pending{false}; // Waits for s, h, or t.
  std::atomic<bool> operator_hold_continue{false}; // Continues an operator-hold state.
  std::atomic<bool> menu_requested{true};       // Grants the menu exclusive stdin access.

  // Defining live nullspace requests. NaN or -1 indicates an empty slot.
  std::atomic<double> nullspace_damping_request{
      std::numeric_limits<double>::quiet_NaN()}; // [N m s/rad].
  std::atomic<double> nullspace_sigma_gain_request{
      std::numeric_limits<double>::quiet_NaN()}; // [N m].
  std::atomic<double> nullspace_probe_step_deg_request{
      std::numeric_limits<double>::quiet_NaN()}; // Probe step [deg].
  std::atomic<int> nullspace_mode_request{-1};   // Encoded NullspaceMode [-].

  std::atomic<char> run_mode_request{0}; // s = sequence; t = contact-impedance hold.

  // Defining live contact establishment-gain requests in surface-axis order.
  std::array<std::atomic<double>, 3> contact_establishment_kp_request; // Kp [N/m].
  std::array<std::atomic<double>, 3> contact_establishment_kr_request; // KR [N m/rad].

  // Defining live compliance-center requests.
  std::array<std::atomic<double>, 3> contact_establishment_compliance_center_mm_request; // EE [mm].
  // r_c = p_C - p_TCP, in surface axes.
  std::array<std::atomic<double>, 3> contact_establishment_rc_mm_request; // [t1,t2,n] [mm].

  // Defining tool-axis tilt for the next sequence [tangent1,tangent2] [deg].
  std::array<std::atomic<double>, 2> contact_establishment_tilt_deg_request;

  /// Initializes each numerical request slot with the empty NaN marker.
  KeyboardSignals() {
    const double none = std::numeric_limits<double>::quiet_NaN();
    for (int i = 0; i < 3; ++i) {
      contact_establishment_kp_request[i].store(none);
      contact_establishment_kr_request[i].store(none);
      contact_establishment_compliance_center_mm_request[i].store(none);
      contact_establishment_rc_mm_request[i].store(none);
    }
    for (int i = 0; i < 2; ++i) {
      contact_establishment_tilt_deg_request[i].store(none);
    }
  }
};

/// Stores the impedance matrices derived from the controller configuration.
struct StateImpedanceGains {
  Mat3 R_base_surface = Mat3::Identity(); // Surface frame expressed in base [-].

  Mat3 Kp_approach = Mat3::Zero(); // Approach translational stiffness [N/m].
  Mat3 Dp_approach = Mat3::Zero(); // Approach translational damping [N s/m].
  Mat3 KR_approach = Mat3::Zero(); // Approach rotational stiffness [N m/rad].
  Mat3 DR_approach = Mat3::Zero(); // Approach rotational damping [N m s/rad].

  Vec3 contact_establishment_Kp_active_diag = Vec3::Zero(); // Selected contact establishment stiffness diagonal [N/m].
  Vec3 contact_establishment_Dp_active_diag = Vec3::Zero(); // Selected contact establishment damping diagonal [N s/m].
  Mat3 Kp_contact_establishment = Mat3::Zero(); // Contact translational stiffness [N/m].
  Mat3 Dp_contact_establishment = Mat3::Zero(); // Contact translational damping [N s/m].
  Mat3 KR_contact_establishment = Mat3::Zero(); // Contact rotational stiffness [N m/rad].
  Mat3 DR_contact_establishment = Mat3::Zero(); // Contact rotational damping [N m s/rad].

  Mat3 Kp_hold = Mat3::Zero(); // Hold translational stiffness [N/m].
  Mat3 Dp_hold = Mat3::Zero(); // Hold translational damping [N s/m].
  Mat3 KR_hold = Mat3::Zero(); // Hold rotational stiffness [N m/rad].
  Mat3 DR_hold = Mat3::Zero(); // Hold rotational damping [N m s/rad].

  Vec3 operator_hold_Kp_active_diag = Vec3::Zero(); // Selected hold stiffness [N/m].
  Vec3 operator_hold_Dp_active_diag = Vec3::Zero(); // Selected hold damping [N s/m].
  Vec3 operator_hold_KR_active_diag = Vec3::Zero(); // Selected hold stiffness [N m/rad].
  Vec3 operator_hold_DR_active_diag = Vec3::Zero(); // Selected hold damping [N m s/rad].
  Mat3 Kp_operator_hold = Mat3::Zero(); // Hold-state translational stiffness [N/m].
  Mat3 Dp_operator_hold = Mat3::Zero(); // Hold-state translational damping [N s/m].
  Mat3 KR_operator_hold = Mat3::Zero(); // Hold-state rotational stiffness [N m/rad].
  Mat3 DR_operator_hold = Mat3::Zero(); // Hold-state rotational damping [N m s/rad].
};

/// Stores damping matrices evaluated or selected at state entry.
struct StateDampingCache {
  bool approach_computed = false; // Indicates initialized approach damping.
  bool contact_establishment_computed = false;    // Indicates initialized contact establishment damping.
  bool hold_computed = false;     // Indicates initialized hold damping.
  bool operator_hold_computed = false;    // Indicates initialized hold-state damping.

  Mat3 Dp_approach = Mat3::Zero(); // [N s/m].
  Mat3 DR_approach = Mat3::Zero(); // [N m s/rad].
  Mat3 Dp_contact_establishment = Mat3::Zero();    // [N s/m].
  Mat3 DR_contact_establishment = Mat3::Zero();    // [N m s/rad].
  Mat3 Dp_hold = Mat3::Zero();     // [N s/m].
  Mat3 DR_hold = Mat3::Zero();     // [N m s/rad].
  Mat3 Dp_operator_hold = Mat3::Zero();    // [N s/m].
  Mat3 DR_operator_hold = Mat3::Zero();    // [N m s/rad].

  // Defining the damping diagonals reported in each state frame.
  bool contact_establishment_damping_valid = false;
  Vec3 contact_establishment_Dp_used = Vec3::Zero();    // [N s/m].
  Vec3 contact_establishment_DR_used = Vec3::Zero();    // [N m s/rad].
  bool approach_damping_valid = false;
  Vec3 approach_Dp_used = Vec3::Zero(); // [N s/m].
  Vec3 approach_DR_used = Vec3::Zero(); // [N m s/rad].
  bool operator_hold_damping_valid = false;
  Vec3 operator_hold_Dp_used = Vec3::Zero();    // [N s/m].
  Vec3 operator_hold_DR_used = Vec3::Zero();    // [N m s/rad].
  bool hold_damping_valid = false;
  Vec3 hold_Dp_used = Vec3::Zero();     // [N s/m].
  Vec3 hold_DR_used = Vec3::Zero();     // [N m s/rad].
};

/// Stores the final state and chronological samples returned by one run.
struct RunResult {
  bool descend_failed = false;        // Indicates an unsuccessful surface approach.
  Vec7 q_start = Vec7::Zero();        // Joint posture at run start [rad].
  Vec7 final_q = Vec7::Zero();        // Joint posture at run end [rad].
  Vec3 final_p_d = Vec3::Zero();      // Final desired TCP position [m].
  Vec3 final_p_EE = Vec3::Zero();     // Final measured TCP position [m].
  Vec3 final_e_p = Vec3::Zero();      // Final translational error [m].
  Vec3 final_e_R = Vec3::Zero();      // Final orientation error [rad].
  std::vector<LogData> log;           // Chronological control samples.
};
